name: hello
on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: message the user
              run: echo $USER

    details:
        runs-on: ubuntu-latest
        steps:
            - name: docker and python version
              run: docker --version && python --version

          
    
